### ISSUE TITLE
应该在文档中明确指出 transion.attr 和 sprite.attr 传入参数是不同的

### ISSUE THREAD

**Issue by MwumLi** [spritejs/sprite-core#39]
在使用过程中, 想对 sprite 的属性做一个过渡效果, 却发现下面这样使用会报错:  
```
sprite.transition(0.5).attr({border: [1, 'red']});
```
最终在源码中发现，原来 `sprite.attr` 和 `transion.attr` 方法的对属性的值并不兼容, `transtion.attr` 的属性值取决于效果的实现, 比如 [effects.border](https://github.com/spritejs/sprite-core/blob/master/src/modules/animation/animation.js#L135-L139)。  

两个实例方法名一样，目标都是更新元素属性，在没有明确文档指出的情况，普通人肯定会认为两者参数一致，但是实际上属性值不一定相同。  
如果不认为这是一个设计 bug, 我觉得应该在文档中明确指出，而不是说给出几个实例用法，否则可能更多的人在使用过程中都会出现类似的错误，到时候可能有大量的 issues

**Comment by akira-cn** [comment]
的确是bug，我修一下
